apiVersion: v1
kind: ConfigMap
metadata:
  name: go-auth
  namespace: go-aestival-dev
data:
  config.yml: |-
    engine:
      port: 80
      # 环境 dev | test | pre-prod | release
      mode: dev
      
    mysql:
      dsn: user:password@tcp(mysql:3306)/go_auth?charset=utf8mb4&parseTime=True&loc=Local
