engine:
  port: 8600
  # 环境 dev | test | pre-prod | release
  mode: dev

mysql:
  dsn: root:root123456@tcp(127.0.0.1:3306)/go-auth?charset=utf8mb4&parseTime=True&loc=Local

redis:
  addrs:
    - 127.0.0.1:6379
    - 127.0.0.1:6380
  username: ""
  password: ""
  pool_size: 10

log:
  level: info
  filename: ./logs/app.log
  max_size: 100
  max_age: 30
  max_backups: 3
  compress: true

geo:
  path: ./scripts/GeoLite2-City.mmdb
